# Add application configuration variables here, as shown below.

development:
  db_user: root
  db_password: 

test:
  db_user: n/a using sqlite
  db_password: n/a using sqlite

production:
  db_user: ...
  db_password: ... 
