
base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

development:
  <<: *base
  host: localhost
  database: beehouse_development
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>

test:
  #pool: 5
  #timeout: 5000
  # These setting work on travis too
  adapter: sqlite3
  #database: ":memory:"
  database: db/test.sqlite3
  timeout: 500

production:
  <<: *base
  database: beehouse_production
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>
  host: sqlreadwrite.brightbox.net
  
