
base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

development:
  <<: *base
  host: localhost
  database: beehouse_development
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>

# development:
#   adapter: postgresql
#   host: localhost
#   encoding: unicode
#   database: beehouse_development

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *base
  database: beehouse_production
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>
  host: sqlreadwrite.brightbox.net
  
